### ISSUE TITLE
Receiving an error when running the speed-test command

### ISSUE THREAD

**Issue by sweatynate** [ddsol/speedtest.net#27] opened 2016-07-15 23:21 UTC
speed-test
> events.js:154
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'settings' of null
    at gotServers (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:522:20)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:48:16
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:238:7
    at Parser.<anonymous> (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:494:16)
    at Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:535:19)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:236:5

**Comment by ddsol** [comment] 2016-07-15 23:38
Dupe of #25

**Closed by ddsol** 2016-07-15 23:38 UTC
