### ISSUE TITLE
When installing it it crashes the whole Home Assistant for an extended period

### ISSUE THREAD

**Issue by soundslikeluke** [ddsol/speedtest.net#119] opened 2021-02-26 08:53 UTC
When I install this it crashes the whole Home Assistant and keeps it offline for extended periods of time. When I removed it it was fine then as soon as I went to configure it it crashed again.

**Comment by ddsol** [comment] 2021-02-26 15:10
I have no idea why it might be crashing for you. I am not able to reproduce it. I also don't have time to try to debug your particular use case, so I'm closing this issue.

**Closed by ddsol** 2021-02-26 15:10 UTC
